plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-ccs-computing.github.io
baseurl: "/W24-20C"

course: "CMPTGCS 20C"
qtr: "W24"
instructor: "Richert Wang"
quarter: "Winter 2024"
piazza_url: 
gauchospace_course_page:
gradescope_class_url:

github_url: https://github.com/ucsb-ccs-computing/W24-20C

start_week: 1
start_date: 2024-01-07 00:00:00.00-7:00
num_weeks: 10
extra_exam_week: true

cal_dates: >                                                                    
  [                                                                            
    {"label":"W24 1st day of instruction", "date":"2024-01-08" },
    {"label":"MLK Jr. Day", "date":"2024-01-15" },
    {"label":"Presidents' Day", "date":"2024-02-19" },
    {"label":"Pong Game Due", "date":"2024-01-29" },
    {"label":"Educational Game Due", "date":"2024-02-21" },
    {"label":"Group Project M1 Due", "date":"2024-02-18" },
    {"label":"Group Project M2 Due", "date":"2024-03-03" },
    {"label":"Group Project M3 Due", "date":"2024-03-13" },
    {"label":"W24 instruction ends", "date":"2024-03-15" },
    {"label":"Lightning Talk Due", "date":"2024-03-04" },                   
    {"label":"W24 qtr ends", "date":"2024-03-22" }                              
  ]

kramdown:
   parse_block_html: true
   default_lang: cpp

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lectures:
    output: true
    permalink: /lectures/:path/
  info:
    output: true
    permalink: /info/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  -
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
